[package]
name = "std-pandoc"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
anyhow = "1.0.89"
brack-pdk-rs = { git = "https://github.com/brack-lang/brack-pdk-rs", version = "0.1.0" }
extism-pdk = "1.2.1"
